### ISSUE TITLE
Implement new circular visualization band

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#45]
This single, 4-part band replaces all existing progress bars -- implement on `newviz` branch *

* The 4 parts are  `rural`, `urban`, `shared`, `free` with values computed [here](https://github.com/dhowe/ramble/blob/newviz/main.js#L140)
* The 4 parts sum to 1 or 100%, so no overlaps and no alpha needed
* `state.domain` holds current domain, either `rural` or `urban`, shared should start from end of this part of bar
* The 4 band-colors (plus initial color) are [here](https://github.com/dhowe/ramble/blob/newviz/main.js#L26)
* The entire band should start light-gray(`bandColors[4]`), and only change to color once updating begins 
* Other notes: 
  * Current values are displayed in the stats panel
  * Most of progress bar stuff is now in [interface.js](https://github.com/dhowe/ramble/blob/newviz/interface.js)
  * Hit the 'd' key to force start the updates

### Todo

- [x] create band with 4 parts: { `rural`, `urban`, `shared`, `free` }:
* `rural` starts at 12, goes CW
* `urban` starts at 12, goes CCW
* `shared` starts at end of current domain, goes in same direction (see note above)
* `free` is basically the remainder (`progress-bar.trail-color`)
- [x] update legend to have 4 parts, with corresponding colors (mostly done)
- [x] existing colors and all strict stuff can be removed
 
See discussion in #44

**Comment by shadoof** [comment]
Thanks both! Looks right to me (so long as `repIds` is the array of replaceable words with no `stops`, as I'm sure it is) and also to note that:
- One of the values need not be calculated/animated. For example: whenever the visualization becomes active, the circular band could be rendered in the color for `free` with the other three parts of the visualization simply rendered on top of it (as specified) with 100% opacity. Any "gap" would reveal the `free` color and would be equal to the `free` metric.
- (I guess, because of the updating pattern) the jump of `shared` from the end of `urban`, say, to the end of `rural` will be striking to see and a good visual indication of when `state.domain` switches.

**Comment by Real-John-Cheung** [comment]
![圖片](https://user-images.githubusercontent.com/61215358/166459673-e7ec98eb-7356-4704-b7d1-6523b165d696.png)
![圖片](https://user-images.githubusercontent.com/61215358/166459987-e9b8e9e6-db91-46e5-b2d4-34199726b0e0.png)

**Comment by Real-John-Cheung** [comment]
fixed brandwidth
![圖片](https://user-images.githubusercontent.com/61215358/166462242-75370f96-cfcd-4c5b-8118-65802ece3d03.png)
![圖片](https://user-images.githubusercontent.com/61215358/166462315-57841bed-c34b-4e10-8732-6be286a1a405.png)

**Comment by dhowe** [comment]
looks good!

**Comment by shadoof** [comment]
Bug in current version, 1.0.44, on this `newviz` branch.

**Desired behavior** `found` part (purple) of the visualization should always extend from current `domain` part.

_Initial_ current behavior, when updating starts:
-  `found` part is on the `urban` CCW side of the circle.

_Initial_ desired behavior:
- `found` section is on CW side of the circle and should extend (further CW) from the `rural` (blue) part, because `domain` is initially `rural`.

Subsequent current behavior:
- When `domain` switch the _first_ time, only, `found` moves suddenly to extend from `rural` (blue). This is wrong.
- It also never switches back to extend from 'urban` (red).

Subsequent desired behavior:
- First fix initial behavior, then
- `found` part should switch whenever `domain` switches to extend, visually, from the current `domain` part. Switch will probably be OK if it is sudden; could also be graphically transitioned in some way if this is easy to implement.

This situation is probably "my bad" since my initial spec was set out "as if" `urban` was the current `domain`. But the subsequent not switching back and forth on `domain` switch amounts to a bug.

Otherwise: This does look great!

**Comment by shadoof** [comment]
Actually. `found` does switch on `domain` switch, but:

Because _initial_ setup is wrong (because `found` is initially on the CCW `urban` side of the circle), it switches wrongly when it switches.

**Comment by shadoof** [comment]
OK. I see. Then `shared` should extend from the whichever `domain` part is ***not*** current.

**Comment by Real-John-Cheung** [comment]
<img width="958" alt="螢幕截圖 2022-05-04 上午10 28 21" src="https://user-images.githubusercontent.com/61215358/166615737-cb0c0a7d-1b69-437e-bdb3-9d85e4e81b5c.png">
